services:
  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - dev-db
    restart: no
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    networks:
      - dev-db
    restart: no
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_PASSWORD}@email.com
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

networks:
  dev-db:
    name: dev-db